name: Node.js Package

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0

      - name: Install Dependencies and Build
        run: |
          npm install --ignore-scripts --omit="@storybook*"
          npm run build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
          registry-url: https://registry.npmjs.org/

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Publish to npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
